name: CI

on:
  push:
    branches: [ task5 ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd task5
          git clone https://github.com/google/googletest.git
          mkdir 3rdparty
          cd 3rdparty
          mv ../googletest .
          cd ..
          mkdir build
          cd build
          cmake ..
          make
          cd ..
          cd ..
          tree
      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path: ./bin/CTestExe
          report-path: report.xml
          working-directory: task5
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: |
           ./task5/lib
           ./task5/bin
